### ISSUE TITLE
Rapid memory leak in vips_text() - if autofit and not cached

### ISSUE THREAD

**Issue by keiviv** [libvips/lua-vips#34]
#### Details
If text() is called with _height_ and _width_ params (i.e. box autofit), and the text is different for each call (i.e. the image is not cached) — it very rapidly leaks memory on every loop, until a crash.

This is likely not specific to Lua, but I only have access to it atm.

#### Reproduction
```lua
-- Shortest working example:
local vips = require('vips')
for i = 1, 1000 do -- unique text
    vips.Image.text(tostring(i) .. 'see mem usage', { width = 100, height = 100 })
end
```
**or**
```lua
local vips = require('vips')
vips.cache_set_max(0) -- emulate unique
for i = 1, 1000 do
    vips.Image.text('see mem usage', { width = 100, height = 100 })
end
```

#### Location
text.c → vips_text_autofit() → likely vips_text_get_extents() → likely pango_layout_get_pixel_extents() unreffing. Can't tell more due to being on a toaster :(

#### P.S. 
As a new libvips adept I can't thank @jcupitt enough for the bindings, guides, examples and overall support <3.

**Comment by jcupitt** [comment]
Hi @keiviv,

Thanks for the report. I tried this:

```lua
local vips = require('vips')
vips.cache_set_max(0)
for i = 1, 1000 do
    vips.Image.text(tostring(i) .. 'see mem usage', { width = 100, height = 100 })
end
```

And I see a fairly steady ~60mb of memory used by luajit. It bumps up and down a bit with GC, but it doesn't go over about 80mb.

Without the `cache_set_max`, you're right, you'll see high memory use. libvips will cache the calls to text, and each call is generating a bitmap, so it'll cache the bitmaps too. If you turn the cache down to 10 (for example) you should see sane memory use but still have the advantages of the operation cache.

Some old versions of libvips did have a leak in autofit, I think, so it might be worth checking which library version you are using.

**Comment by jcupitt** [comment]
(for mem use I watched RES in `top`).

**Comment by keiviv** [comment]
This is weird — this exact code you don't go over 80Mb goes to ~350Mb on my platform until it crashes every time. 

Platform: W10x64 LTSB, LuaJIT 2.1 Resty fork, Vips 8.8 mozjpeg.

Any chance this might be platform-specific? There is a comment in text.c:

> This does not unref cleanly on many platforms, so we will leak horribly
 unless we reuse it. Sadly this means vips_text() needs to use a lock 
 internally to single-thread text rendering.

Wondering if this might have something to do with it, or I'm just cursed specifically, for my many sins.

**Comment by kleisauke** [comment]
Could you try libvips v8.9.2? Perhaps commit https://github.com/libvips/libvips/commit/c84a43f27765066b78c9c383489fb68e10d67d96 fixes this.

**Comment by keiviv** [comment]
Yup, just installed everything latest and vanilla, and there are **no leaks after multiple tests**. So it's likely an older version issue, even though I can't see anything related in the patch notes between 8.8 and 8.9.2.

Guess the issue is closed, and the moral is — update first, and only then trouble John and Kleis with reports. 

P.S. @kleisauke, huge thanks for the mozjpeg option. Any chance you have binaries for the latest version, like you've [posted for 8.8](https://github.com/libvips/build-win64-mxe/issues/8#issuecomment-500236157)?

**Comment by jcupitt** [comment]
Ah could be. I was testing on Ubuntu.

Text rendering is really complex and interacts with a revolting mix of cross-platform and platform libraries. The problem could be any any one of about 10 packages that libvips pulls in for text :(

**Comment by jcupitt** [comment]
... and you should try with current stable, as Kleis says.

**Comment by keiviv** [comment]
I did, and closed the issue. Thank you, Kleis and everyone for such a wonderful library, and the fixes.

**Comment by kleisauke** [comment]
I'll try to update https://github.com/libvips/build-win64-mxe/issues/8 to the latest libvips version (v8.9.2). Note that I do not officially support and test the MozJPEG build, it's done on a best effort basis.

**Comment by kleisauke** [comment]
I've updated the 64-bit libvips Windows binaries built with MozJPEG within that issue. @keiviv Let me know if that works for you.

Note that these binaries were built against the [`drop-vista-xp`](https://github.com/libvips/build-win64-mxe/tree/drop-vista-xp) which could contain incompatibilities due to a major MinGW-w64 and GCC update (it will need some further testing/benchmarking before this is included in master). As the branch name says, Windows XP and Vista is also not supported anymore (I doubt if this has worked in the past, since I only test these binaries on Windows 10).

As an aside,
Hopefully when libjpeg-turbo supports the `jpeg_c_int_param_supported` and `jpeg_c_bool_param_supported` functions (i.e. what is `ifdef`'d with `HAVE_JPEG_EXT_PARAMS`) one should just able to replace the `libjpeg-62.dll` with the MozJPEG provided DLL. https://libjpeg-turbo.org/About/Mozjpeg is also relevant here.

**Comment by keiviv** [comment]
Many thanks, @kleisauke — it all works without any issues on W10 (like you, I only cant test it on that). I did a rather big test (50k unique images with processing and writes in a single loop), both Vips and MozJPEG worked without a hiccup.

It's very kind of you to build and share the MozJPEG builds — due to my circumstances it would take me ages to build one, even via docker, and I'm sure I'm not the only one. Have you ever thought of incorporating it into the main build cycle — as a variant of the web version of the distribution? MozJPEG is the most used jpeg optimizer, so it would make sense for a web-related build. 

As to the original issue itself — as you've guessed right away it was caused by that Pango unref bug, and after more testing — can confirm that only by that, and nothing else — so my report was a 100% duplicate. I thought it was unique because the fix was not mentioned in the changelog — I did a Ctrl-F for "text" before reporting, and there was no mention of it after v.8.8  (earliest was a v.8.7.2 fix). At least I've guessed the bug location within text.c close enough, and code was narrow enough for a smart person to guess the cause quickly. Thanks again for that.

**Comment by jcupitt** [comment]
The changelog for minor releases only lists substantial changes -- it'd be huge if we had everything in there.

The git log has it:

```
$ git log --grep text
commit 664796acab0d3e08e41be16e37c6161fb387d823
Author: John Cupitt <jcupitt@gmail.com>
Date:   Thu Dec 26 14:11:15 2019 +0000

    relax text test render threshold
    
    so we pass on win as well, see https://github.com/libvips/libvips/commit/981ffe752b3d043d3b1eef48bb6b250da99f958c#r36581177

commit c84a43f27765066b78c9c383489fb68e10d67d96
Author: John Cupitt <jcupitt@gmail.com>
Date:   Sat Dec 21 12:56:09 2019 +0000

    fix memleak in vips_text()
    
    We were not unreffing PangoLayout. Thank you uint128!
    
    See https://github.com/libvips/libvips/issues/1508

...
```

**Comment by keiviv** [comment]
Yep, I've found it after the fact, and not blaming anyone for not mentioning it, of course. 

Not sure if it was minor or not — it quite literally made autofit unusable — so it's major. But text() is just one of many Vips functions — so it's... not major. In any case — thank you for being Holmes anyway, took you just a minute to solve this crime.

Btw — it was a crime, and a horrible one. It was crashing with the most unhelpful and unrelated message — complaining that Pango cannot load Verdana.ttf from Windows/Fonts. Took me hours to stop wondering why it was trying to load it (my font param was different), why it cannot load it if it so bloody wants it (I have it there), if there is something wrong in numerous lines of code I wrote before testing it on a big set (it didn't crash on short test-as-you-code loops), if there is God (an is it a DJ), and only after that — what's in text.c actually. 

I respect Vips so much it was absolutely the last one to blame, and after hours of staring at own code I could only Ctrl+F the changelog, hence the duplicate.

Thank you again <3

**Comment by jcupitt** [comment]
I wasn't being defensive, just saying that the changelog doesn't have everything. I'm glad your code is now working!

**Comment by kleisauke** [comment]
> Have you ever thought of incorporating it into the main build cycle — as a variant of the web version of the distribution? MozJPEG is the most used jpeg optimizer, so it would make sense for a web-related build.

I'm not considering including it in the main build cycle, as MozJPEG is at the expense of performance. It may be useful in some situations, but in most cases libjpeg-turbo fits better to users' needs.

Users are always free to build their own binaries with MozJPEG included, it should be straightforward.

**Comment by keiviv** [comment]
For general use, Turbo beats Moz, but specifically for web nothing out there beats Moz — despite what the Turbo devs said in their statement about merging with Moz. 

Moz is a de-facto standard for the web — everyone (except Google, who has its own (slower) lib called [Guetzli](https://en.wikipedia.org/wiki/Guetzli)) uses it. 

I myself tried to switch to something better (I deal with tens on thousands of images, so every millisecond is precious) — but each time after most thorough testing (every possible option combination, even own quantization tables, etc) I get back to Moz. There is a reason Mozilla is not just using Turbo — and it's, despite what Turbo said — a very valid reason — the size/time/quality ratio — that nothing else beats.

I not expecting to change your mind, of course, just sharing the perspective. I think it would make sense to have both the current 'web' distro, and maybe a 'web-optimized' one if it could be automated — but your perspective is, of course, more important.

I'm grateful for your Moz binaries, huge thanks for sharing, even though you don't have to do it.
