### ISSUE TITLE
Using VIPs library and Lua to process pictures

### ISSUE THREAD

**Issue by hzm199822** [libvips/lua-vips#37]
To get an original picture from the file, what I want to do is to select a position, cut a rectangle, and make a concave or convex semicircle on the edge of the rectangle, and make this area transparent. Is there an appropriate API or solution?

**Comment by jcupitt** [comment]
Hi @hzm199822, could you post a sample image showing what you want?

**Comment by jcupitt** [comment]
For example, this:

```lua
#!/usr/bin/luajit

local vips = require "vips"

local im = vips.Image.new_from_file(arg[1], {access = "sequential"})

-- make a transparent square ... just RGBA all 0 (black)
local square = vips.Image.black(64, 64, {bands = 4})

-- insert into the main image
im = im:insert(square, 100, 100)

im:write_to_file(arg[2])
```

makes a square in an image transparent, eg.:

```
$ ./try320.lua ~/pics/lion.png x.png
```

![x](https://user-images.githubusercontent.com/580843/97990720-46a08b00-1dd8-11eb-931a-f9aa9e5d45ac.png)

Where do you need the semicircle? Do you need a line, or a segment?

**Comment by hzm199822** [comment]
![Uploading 1111.png…]()

**Comment by hzm199822** [comment]
What I want is not all white, but translucency. Or that piece becomes a watermark

**Comment by hzm199822** [comment]
What I want is that this square is just a benchmark. I want to add a semicircle or subtract a semicircle on any two sides of the four sides of the square. Of course, the diameter of the semicircle must be smaller than the side length

**Comment by hzm199822** [comment]
What I want is that this square is just a benchmark. I want to add a semicircle or subtract a semicircle on any three sides of the four sides of the square. Of course, the diameter of the semicircle must be smaller than the side length.
The translucency on the right side of the image can also be a fuzzy watermark. Then the block on the left side, I hope, is the same as the missing block in the original image, which is equivalent to providing a picture. I need to make two images, one is with watermark, the other is a small piece taken out separately

I don't know if luavips can do this for images (add or subtract semicircles on the edges of rectangles)




huangzhiming
zm.huang@ucloud.cn


签名由 网易邮箱大师 定制


On 11/3/2020 21:23，John Cupitt<notifications@github.com> wrote：


Hi @hzm199822, could you post a sample image showing what you want?

**Comment by hzm199822** [comment]
What I want is that this square is just a benchmark. I want to add a semicircle or subtract a semicircle on any three sides of the four sides of the square. Of course, the diameter of the semicircle must be smaller than the side length.
The translucency on the right side of the image can also be a fuzzy watermark. Then the block on the left side, I hope, is the same as the missing block in the original image, which is equivalent to providing a picture. I need to make two images, one is with watermark, the other is a small piece taken out separately
I don't know if luavips can do this for images (add or subtract semicircles on the edges of rectangles)

**Comment by jcupitt** [comment]
The square in the lion only looks white because the page background is white. Try opening the image in a new tab.

You can overlay complex shapes with `composite`. You give it an RGBA image, one of the PDF blending modes (eg. `over`) and a position. 

Could you upload some test images? It would save me making them. Just drag the images into the text box.

**Comment by hzm199822** [comment]
huangzhiming
zm.huang@ucloud.cn


签名由 网易邮箱大师 定制


On 11/4/2020 15:58，John Cupitt<notifications@github.com> wrote：


The square in the lion only looks white because the page background is white. Try opening the image in a new tab.
You can overlay complex shapes with composite. You give it an RGBA image and one of the PDF blending modes (eg. over) and a position.
Could you upload some test images? It would save me making them. Just drag the images into the text box.

**Comment by jcupitt** [comment]
Composite example:

```lua
#!/usr/bin/luajit

vips = require 'vips'

local image = vips.Image.new_from_file(arg[1], {access = "sequential"})
local overlay = vips.Image.new_from_file(arg[2], {access = "sequential"})

-- composite the overlay at 50, 20 using 'over' blend mode
image = image:composite(overlay, "over", {x = 50, y = 20})

image:write_to_file(arg[3])
```

Generates:

![x](https://user-images.githubusercontent.com/580843/98086825-2ecc1400-1e77-11eb-95d4-ae30e2b16ff9.jpg)

**Comment by hzm199822** [comment]
I mainly want to extract a figure from the original image, then save it, and change the extracted part of the original image into translucent or other

**Comment by hzm199822** [comment]
It's important to extract this step, but it seems to me that the API can only extract simple rectangles

**Comment by jcupitt** [comment]
You can apply masks if you want more complex shapes.

Post a set of sample images and I'll have a go.

**Comment by hzm199822** [comment]
like this?


huangzhiming
zm.huang@ucloud.cn


签名由 网易邮箱大师 定制


On 11/4/2020 17:07，John Cupitt<notifications@github.com> wrote：


You can apply masks if you want more complex shapes.
Post a set of sample images and I'll have a go.

**Comment by jcupitt** [comment]
Use the github website and drag images into the text box.

**Comment by hzm199822** [comment]
![Uploading 图片.png…]()

**Comment by jcupitt** [comment]
You need to wait for the upload to finish before pressing `Comment`.

**Comment by hzm199822** [comment]
![图片](https://user-images.githubusercontent.com/68108652/98096073-441c5f00-1ec6-11eb-82ff-7f9a8ed843e1.png)

**Comment by hzm199822** [comment]
OK, now it's OK. My goal is very simple, that is to get such a shape from the original image rather than just a simple rectangle. After saving this shape, I will do some operations on the original image, such as translucency, or other things. I can now extract rectangles and darken them myself, but I don't know if there is such an API to support my goal.

**Comment by jcupitt** [comment]
Ah, like a jigsaw, I wondered.

Yes, it should be easy. Do you have that shape as a PNG?

**Comment by hzm199822** [comment]
![8](https://user-images.githubusercontent.com/68108652/98096530-d3297700-1ec6-11eb-8c7e-7ed6a6fa754a.jpg)
![square_back](https://user-images.githubusercontent.com/68108652/98096551-da508500-1ec6-11eb-9c9a-d3db1677d134.jpg)
![background](https://user-images.githubusercontent.com/68108652/98096552-dc1a4880-1ec6-11eb-85e6-f8d1bbbacc24.jpg)

**Comment by hzm199822** [comment]
What I want to do is JPG, the encoding format of JPG is simpler than PNG, and the operation time should be shorter

**Comment by jcupitt** [comment]
I mean, do you have a PNG for the jigsaw piece? It would save me drawing it.

**Comment by hzm199822** [comment]
![图片](https://user-images.githubusercontent.com/68108652/98097461-00c2f000-1ec8-11eb-8532-ef5e12660028.png)

**Comment by hzm199822** [comment]
![图片](https://user-images.githubusercontent.com/68108652/98097626-37006f80-1ec8-11eb-80aa-11f1573a597b.png)

**Comment by hzm199822** [comment]
like this?

**Comment by jcupitt** [comment]
I found this sample:

![jigsaw](https://user-images.githubusercontent.com/580843/98099193-2aa7f280-1e87-11eb-8974-d9bf8585b8eb.png)

Example code:

```lua
#!/usr/bin/luajit

vips = require 'vips'

local image = vips.Image.new_from_file(arg[1], {access = "sequential"})
local mask = vips.Image.new_from_file(arg[2], {access = "sequential"})

-- the position we place the piece
left = 200
top = 100

-- get just the alpha from the mask
alpha = mask:extract_band(3)

-- image pixels
rgb = image:crop(left, top, mask:width(), mask:height())

-- brighten 50%
rgb = rgb * 1.5

-- attach the mask as the alpha channel
overlay = rgb .. alpha

-- composite back
image = image:composite(overlay, "over", {x = left, y = top})

image:write_to_file(arg[3])
```

I can run like this:

```
$ ./try320.lua ~/pics/Gugg_coloured.jpg ~/pics/jigsaw.png x.jpg
```

To make this:

![x](https://user-images.githubusercontent.com/580843/98099149-2085f400-1e87-11eb-9cba-928cfe2a5542.jpg)

**Comment by hzm199822** [comment]
no...

**Comment by hzm199822** [comment]
What I want to do is to get a jigsaw block from the original image, not a rectangle, because I need this puzzle block to do some operations. This jigsaw block comes from the original picture, and the position obtained from the original image is different each time

**Comment by jcupitt** [comment]
Sorry, I still don't understand what you want to do.

Are you trying to hide or remove the watermark?

**Comment by hzm199822** [comment]
![4fe01a4819e02fbfce70f3cd0dbbe491](https://user-images.githubusercontent.com/68108652/98100585-09b5c080-1ecc-11eb-86eb-fd59efa31a75.jpg)

**Comment by hzm199822** [comment]
local vips = require"vips.vips"

local background = "/home/hzm/hzm/vips/8.jpg"
local back = vips.Image.new_from_file(background)
math.randomseed(tonumber(tostring(os.time()):reverse():sub(1,7)))
local s = os.clock()
local random_left = math.random(512,914)
local random_top  = math.random(1,626)
local random_length = math.random(81,100)
local square_black = vips.Image.black(random_length,random_length,{bands = 3})

local square_back = vips.Image.crop(back,random_left,random_top,random_length,random_length)
back = back:insert(square_black,random_left,random_top)
back:write_to_file("/home/hzm/hzm/vips/background.jpg")
square_back:write_to_file("/home/hzm/hzm/vips/square_back.jpg")
local e = os.clock()
print("used time:"..e-s.."seconds")

**Comment by hzm199822** [comment]
thsi api  crop Help me get a rectangle from the original, but I want to get a puzzle block instead of a rectangle. What should I do? I've thought about getting rectangles and two semicircles, but I haven't found the API for getting semicircles

**Comment by jcupitt** [comment]
You just get a rectangle and then apply an alpha to cut the exact shape, like in my example above.

**Comment by hzm199822** [comment]
I don't think I understand this API properly ：extract_band

**Comment by jcupitt** [comment]
Example:

```lua
#!/usr/bin/luajit

vips = require 'vips'

local image = vips.Image.new_from_file(arg[1])
local mask = vips.Image.new_from_file(arg[2]) 

-- the position we take the piece from
from_left = math.random(0, image:width() - mask:width())
from_top = math.random(0, image:height() - mask:height())

-- the position we put the piece back
from_left = math.random(0, image:width() - mask:width())
from_top = math.random(0, image:height() - mask:height())

-- get just the alpha from the mask
alpha = mask:extract_band(3)

-- image pixels
pixels = image:crop(from_left, from_top, mask:width(), mask:height())

-- brighten and darken 50%
brighter = pixels * 1.5
darker = pixels * 0.5

-- attach the mask as the alpha channel
brighter = brighter .. alpha
darker = darker .. alpha

-- composite back
image = image:composite(darker, "over", {x = from_left, y = from_top})
image = image:composite(brighter, "over", {x = to_left, y = to_top})

image:write_to_file(arg[3])
```

To make:

![x](https://user-images.githubusercontent.com/580843/98102852-0ac6fd80-1e8c-11eb-9e5c-485396125c8d.jpg)

I expect you'd like a shadow as well. The easiest way is to draw the shadow on the mask, but you could also compute one with a convolution.

**Comment by jcupitt** [comment]
If you have a three-band image (eg. RGB) you can extract a band like this:

```
g = rgb:extract_band(1)
```

Now `g` is a one-band image (just the green). Bands number from zero.

**Comment by hzm199822** [comment]
I'd like to know how you changed the rectangle into this puzzle. Instead of drawing this puzzle in advance, you took it directly from the original picture

**Comment by hzm199822** [comment]
You mean, let me get a rectangle from the original picture and then turn it into a puzzle?

**Comment by hzm199822** [comment]
The most important thing is to get it directly from the original drawing, not draw it yourself.

**Comment by jcupitt** [comment]
I just took the alpha channel from that jigsaw PNG.

You can draw yourself, of course, if you have something like an SVG of the shape.

**Comment by hzm199822** [comment]
Of course, I know that I can draw by myself, but the effect I want is to take it directly from the original image, because the shape and content are different each time. Do I have to draw again every time? Scholar, can you understand what I mean?

**Comment by hzm199822** [comment]
![8](https://user-images.githubusercontent.com/68108652/98103882-a712f380-1ed0-11eb-8a57-bd9f43a42558.jpg)
![square_back](https://user-images.githubusercontent.com/68108652/98103886-a8dcb700-1ed0-11eb-8546-4b97085cd433.jpg)
![background](https://user-images.githubusercontent.com/68108652/98103888-aaa67a80-1ed0-11eb-957a-52810d7e2de9.jpg)

**Comment by hzm199822** [comment]
local vips = require"vips.vips"

local background = "/home/hzm/hzm/vips/8.jpg"
local back = vips.Image.new_from_file(background)
math.randomseed(tonumber(tostring(os.time()):reverse():sub(1,7)))
local s = os.clock()
local random_left = math.random(512,914)
local random_top = math.random(1,626)
local random_length = math.random(81,100)
local square_black = vips.Image.black(random_length,random_length,{bands = 3})

local square_back = vips.Image.crop(back,random_left,random_top,random_length,random_length)
back = back:insert(square_black,random_left,random_top)
back:write_to_file("/home/hzm/hzm/vips/background.jpg")
square_back:write_to_file("/home/hzm/hzm/vips/square_back.jpg")
local e = os.clock()
print("used time:"..e-s.."seconds")

**Comment by hzm199822** [comment]
I don't believe it. You don't understand what I need

**Comment by jcupitt** [comment]
Instead of

```lua
local square_back = vips.Image.crop(back,random_left,random_top,random_length,random_length)
```

You can write:

```lua
local square_back = back:crop(random_left,random_top,random_length,random_length)
```

No, I don't understand what you mean :-( 

Do you want to detect a jigsaw shape in the original image somehow? Do you know where it is, or do you need to search for it? Is it always the same shape, or do you need to detect any kind of jigsaw shape?

If you can give a clear explanation of what you need, perhaps I can help.

**Comment by hzm199822** [comment]
The original image is a normal 320 * 160 rectangle. I want to cut the next puzzle shape from the original image. I don't know where I need to cut, because I can use random numbers to determine the coordinates I want to cut. I define their shape as a rectangle and two semicircles, which can be concave or convex. I need to cut it off from the original.

**Comment by hzm199822** [comment]
![cf271ab9834f819b3a649dd07976dc26](https://user-images.githubusercontent.com/68108652/98105474-04a83f80-1ed3-11eb-8599-0280d3035765.jpg)

**Comment by hzm199822** [comment]
You know, VIPs provides cuts that I can only find clipping rectangles

**Comment by hzm199822** [comment]
If there is a semicircle, I think I can cut it twice. The first time I cut the rectangle, the second time I cut two semicircles on the edge of the rectangle, and then I can cut the combination again to achieve the desired effect

**Comment by hzm199822** [comment]
When I combine these parts, he is a puzzle shape. I then turn the puzzle into black or white or transparent, and put it on the original picture. That's all right

**Comment by hzm199822** [comment]
![96e210a4f1070a296bc4c2691c19d751](https://user-images.githubusercontent.com/68108652/98106080-da0ab680-1ed3-11eb-94a9-bbe8144f410e.jpg)

**Comment by hzm199822** [comment]
If you still can't understand, forget it

**Comment by hzm199822** [comment]
Thank you for your patience

**Comment by hzm199822** [comment]
I appreciate it

**Comment by jcupitt** [comment]
Maybe like this?

```lua
#!/usr/bin/luajit

vips = require 'vips'

local image = vips.Image.new_from_file(arg[1])

-- for a size x size square, return one of the four edge points randomly
function random_edge(size)
    local edges = {
        {size / 2, 0},
        {size, size / 2},
        {size / 2, size},
        {0, size / 2}
    }
    
    return unpack(edges[math.random(0, 3)])
end 

-- generate a mask ... a square with a semicircle removed from one edge and
-- added to another
local size = 128
local radius = size / 3
local black = vips.Image.black(size + 2 * radius, size + 2 * radius)
local mask = black:draw_rect(255, radius, radius, size, size, {fill = true})
local left, top = random_edge(size)
mask = mask:draw_circle(255, radius + left, radius + top, radius, {fill = true})
local left, top = random_edge(size)
mask = mask:draw_circle(0, radius + left, radius + top, radius, {fill = true})

-- the position we cut the piece from
left = math.random(0, image:width() - mask:width())
top = math.random(0, image:height() - mask:height())

-- crop out the piece and mask
crop = image:crop(left, top, mask:width(), mask:height()) .. mask
crop:write_to_file(arg[2])

-- make a transparent piece to draw on the image
transparent = (black .. black .. black .. mask):copy{interpretation = "srgb"}
image = image:composite(transparent, "dest-out", {x = left, y = top})
image:write_to_file(arg[3])
```

Then:

```
$ ./try320.lua ~/pics/Gugg_coloured.jpg x.png y.png
```

Makes these two images:

![x](https://user-images.githubusercontent.com/580843/98131044-d0bd2200-1eb2-11eb-99f8-6f92b7072fb2.png)

![y](https://user-images.githubusercontent.com/580843/98131059-d450a900-1eb2-11eb-8301-46f1c6287164.png)

**Comment by hzm199822** [comment]
Yeah, that's what I mean

**Comment by hzm199822** [comment]
Oh, I used your example, but why did I cut that piece with black edges? And yours doesn't

**Comment by hzm199822** [comment]
![back](https://user-images.githubusercontent.com/68108652/98191831-fef33e00-1f54-11eb-9fce-c7a2dba2f080.jpg)
![square](https://user-images.githubusercontent.com/68108652/98191832-00246b00-1f55-11eb-9dcc-5ee72b3ad113.jpg)

**Comment by hzm199822** [comment]
哦，你的带了白色的边，我想把这个白色的边去掉，应该如何处理

**Comment by hzm199822** [comment]
Oh, you have a white edge. I want to remove the white edge. What should I do

**Comment by hzm199822** [comment]
How to get rid of the black part of the block to get the puzzle inside

**Comment by hzm199822** [comment]
![04c79f461ec8539d8ef5375f5edb8c11](https://user-images.githubusercontent.com/68108652/98195962-f0f5eb00-1f5d-11eb-9e3e-4f0e50bd0125.jpg)

**Comment by jcupitt** [comment]
Hello again, you need to save as PNG -- jpg images don't support transparency.

**Comment by hzm199822** [comment]
![图片](https://user-images.githubusercontent.com/68108652/98316980-789f3080-2016-11eb-9cb6-cbc4610e7f21.png)
I see. I mean, this is the picture you got, but there are still white edges around it. All I need is the inner part. How to remove the white edge of this part, because I need to put this picture back into the original image, and the white edge will be redundant.

**Comment by jcupitt** [comment]
No, the edges are transparent. Try opening this in a new tab:

![x](https://user-images.githubusercontent.com/580843/98328343-6bba1700-1fed-11eb-8269-abd529700376.png)

**Comment by jcupitt** [comment]
I see:

![x](https://user-images.githubusercontent.com/580843/98328456-b20f7600-1fed-11eb-8184-0e79bd98ec37.png)

**Comment by hzm199822** [comment]
不对啊，他不是透明啊，他就是有颜色的。白色

**Comment by hzm199822** [comment]
No, he's not transparent. He has colors. white

**Comment by hzm199822** [comment]
![98131044-d0bd2200-1eb2-11eb-99f8-6f92b7072fb2qw](https://user-images.githubusercontent.com/68108652/98332547-d5f8a900-2039-11eb-8448-0b0247263829.png)
![98131059-d450a900-1eb2-11eb-8301-46f1c6287164](https://user-images.githubusercontent.com/68108652/98332552-d6913f80-2039-11eb-93a7-75d2ed6d9a93.png)
OK, these two kinds of images are obtained after the previous processing. Now I want to put this small image on this large image and put it at any position. Then, the edge of this small image will block the original pixels of the large image. So I want to get a small image without edges

**Comment by hzm199822** [comment]
You can try to put the small image in any position of the large image, there will be white edge to block part of the original pixel of the large image

**Comment by hzm199822** [comment]
What I want is a small image with no edges, not one with white or black edges

**Comment by hzm199822** [comment]
![图片](https://user-images.githubusercontent.com/68108652/98333026-d80f3780-203a-11eb-8290-b72d1a89da47.png)

**Comment by hzm199822** [comment]
![Uploading 图片.png…]()

**Comment by hzm199822** [comment]
![图片](https://user-images.githubusercontent.com/68108652/98333136-0c82f380-203b-11eb-81ae-14ee85548960.png)

**Comment by hzm199822** [comment]
I want to know if there is an API that can cut the edges of a puzzle directly, just a part in the middle

**Comment by hzm199822** [comment]
![图片](https://user-images.githubusercontent.com/68108652/98333351-80250080-203b-11eb-89b5-361b8efc6e32.png)

**Comment by jcupitt** [comment]
I promise you, there is no white border. Are you converting to JPG at some point? That will remove the transparency.

Download this PNG image (`x.png`):

![x](https://user-images.githubusercontent.com/580843/98333890-a164fd00-1ff9-11eb-9167-3d3a0b319fc5.png)

Now enter this:

```
vips composite2 Gugg_coloured.jpg x.png result.jpg over --x 100 --y 100
```

That will load `Gugg_coloured.jpg`, then composite `x.png` (the jigsaw piece) into the image and save as `result.jpg`. You will see this:

![result](https://user-images.githubusercontent.com/580843/98334093-04ef2a80-1ffa-11eb-8751-9fec5b7ab964.jpg)

No border.

**Comment by jcupitt** [comment]
Do not use JPG for images with transparency. JPG does not support transparent elements.

**Comment by hzm199822** [comment]
![图片](https://user-images.githubusercontent.com/68108652/98334573-1f4af780-203e-11eb-910f-d20e5beadfa2.png)
Put PNG on top of JPG to get a JPG

**Comment by hzm199822** [comment]
But this is only the VIPs API. What I need to do is JavaScript to do this operation. I don't know whether it supports putting PNG in JPG to get jpg

**Comment by hzm199822** [comment]
Only in this way? Or I use PNG for my original image

**Comment by hzm199822** [comment]
![back](https://user-images.githubusercontent.com/68108652/98337385-81f2c200-2043-11eb-8ee8-1307d3f66502.png)
![square](https://user-images.githubusercontent.com/68108652/98337397-87e8a300-2043-11eb-93fd-009b6c54f0cb.png)
![r8](https://user-images.githubusercontent.com/68108652/98337415-8cad5700-2043-11eb-9ea6-3933d1d706ab.png)

**Comment by hzm199822** [comment]
When I generated these images, I saved them all in PNG format. Finally, the white edge can be eliminated by combining the proposite2 function, but I don't know if JS can do the same

**Comment by jcupitt** [comment]
Yes, you can use CSS blending modes to layer images, eg.:

https://getflywheel.com/layout/css-blend-modes/

**Comment by kleisauke** [comment]
Just curious, are you trying to create a jigsaw puzzle out of an image? If so, the SVG loader of libvips could be useful here.

For example, take this zebra image: [zebra.jpg](https://user-images.githubusercontent.com/12746591/98444148-66a1b880-2110-11eb-8748-823886e45e7e.jpg)

And this code:
```lua
#!/usr/bin/luajit

local vips = require "vips"

local filename = "images/zebra.jpg"
local paths = {
    "<path transform=\"translate(56,0)\" d=\"M0,0 L206,0 C198,17 222,78 214,80 C157,37 160,173 221,130 C235,132 215,223 229,240 C213,225 153,244 152,230 C196,168 92,165 106,221 C105,228 16,203 0,211 L0,0\"/>",
    "<path transform=\"translate(45,0)\" d=\"M217,0 L475,0 C460,17 478,92 462,94 C399,66 395,171 450,144 C457,145 430,221 437,238 C425,249 369,227 371,238 C418,298 318,298 335,239 C338,228 252,251 240,240 C226,223 246,132 232,130 C171,173 168,37 225,80 C233,78 209,17 217,0\"/>",
    "<path transform=\"translate(-28,0)\" d=\"M548,0 L757,0 C767,13 743,85 753,84 C811,52 810,154 749,123 C737,121 758,193 746,206 C729,199 654,224 652,217 C680,161 575,165 603,227 C602,242 527,223 510,238 C503,221 530,145 523,144 C468,171 472,66 535,94 C551,92 533,17 548,0\"/>",
    "<path transform=\"translate(-122,0)\" d=\"M851,0 L1066,0 L1066,235 C1051,221 991,240 991,226 C1034,163 930,160 945,216 C944,224 855,199 840,206 C852,193 831,121 843,123 C904,154 905,52 847,84 C837,85 861,13 851,0\"/>",
    "<path transform=\"translate(56,-66)\" d=\"M0,277 C16,269 105,294 106,287 C92,231 196,234 152,296 C153,310 213,291 229,306 C214,319 233,391 219,389 C157,327 153,488 209,427 C217,425 192,497 200,510 C187,521 116,498 118,509 C180,567 20,567 81,507 C84,495 12,517 0,506 L0,277\"/>",
    "<path transform=\"translate(45,-66)\" d=\"M240,306 C252,317 338,294 335,305 C318,364 418,364 371,304 C369,293 425,315 437,304 C426,318 448,392 437,392 C378,363 378,466 437,437 C448,437 426,511 437,526 C422,535 362,511 362,520 C406,578 302,576 316,515 C315,502 226,523 211,510 C203,497 228,425 220,427 C164,488 168,327 230,389 C244,391 225,319 240,306\"/>",
    "<path transform=\"translate(3,-66)\" d=\"M479,304 C496,289 571,308 572,293 C544,231 649,227 621,283 C623,290 698,265 715,272 C726,289 705,351 717,353 C777,311 777,446 719,404 C709,406 732,497 721,514 C704,527 628,506 626,518 C653,579 547,580 575,522 C572,512 496,535 479,526 C468,511 490,437 479,437 C420,466 420,363 479,392 C490,392 468,318 479,304\"/>",
    "<path transform=\"translate(-108,-66)\" d=\"M826,272 C841,265 930,290 931,282 C916,226 1020,229 977,292 C977,306 1037,287 1052,301 L1052,521 C1037,531 978,509 979,519 C1023,577 920,577 935,517 C935,505 847,526 832,514 C843,497 820,406 830,404 C888,446 888,311 828,353 C816,351 837,289 826,272\"/>",
    "<path transform=\"translate(56,-170)\" d=\"M0,610 C12,621 84,599 81,611 C20,671 180,671 118,613 C116,602 187,625 200,614 C215,629 197,718 212,718 C275,703 279,806 223,762 C216,762 242,821 235,836 L0,836 L0,610\"/>",
    "<path transform=\"translate(11,-170)\" d=\"M245,614 C260,627 349,606 350,619 C336,680 440,682 396,624 C396,615 456,639 471,630 C482,643 460,700 471,698 C530,652 530,784 471,738 C460,736 482,823 471,836 L280,836 C287,821 261,762 268,762 C324,806 320,703 257,718 C242,718 260,629 245,614\"/>",
    "<path transform=\"translate(-42,-170)\" d=\"M524,630 C541,639 617,616 620,626 C592,684 698,683 671,622 C673,610 749,631 766,618 C755,633 778,706 767,706 C708,676 708,779 768,749 C779,748 757,822 768,836 L524,836 C535,823 513,736 524,738 C583,784 583,652 524,698 C513,700 535,643 524,630\"/>",
    "<path transform=\"translate(-75,-170)\" d=\"M799,618 C814,630 902,609 902,621 C887,681 990,681 946,623 C945,613 1004,635 1019,625 L1019,836 L801,836 C790,822 812,748 801,749 C741,779 741,676 800,706 C811,706 788,633 799,618\"/>"
}

local main = vips.Image.new_from_file(filename)

for i, path in pairs(paths) do
    local svg = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"" .. main:width() .. "\" height=\"" .. main:height() .. "\">"
    svg = svg .. path ..  "</svg>"

    local im = vips.Image.new_from_buffer(svg, "", {access = "sequential"})

    -- Composite the two images using the PDF "dest-in" mode
    local piece = main:composite(im, "dest-in")

    -- Search for the bounding box of the non-background area
    local left, top, width, height = piece:find_trim({
        threshold = 10,
        background = { 0, 0, 0 },
    })

    -- And crop the jigsaw piece
    if width > 0 and height > 0 then
        piece = piece:crop(left, top, width, height)
    end

    print("writing piece" .. i .. ".png")
    piece:write_to_file("piece" .. i .. ".png")
end
```

To make these jigsaw pieces:
<details>
<summary>Details</summary>

![piece1](https://user-images.githubusercontent.com/12746591/98444192-b08a9e80-2110-11eb-9ca9-9fcb1da9fe68.png)
![piece2](https://user-images.githubusercontent.com/12746591/98444210-b7b1ac80-2110-11eb-9cf7-c8bdd249150c.png)
![piece3](https://user-images.githubusercontent.com/12746591/98444209-b7191600-2110-11eb-913f-a83844d11a9f.png)
![piece4](https://user-images.githubusercontent.com/12746591/98444206-b7191600-2110-11eb-96d3-456d9cc3da10.png)
![piece5](https://user-images.githubusercontent.com/12746591/98444205-b6807f80-2110-11eb-8608-5ed93005c5b5.png)
![piece6](https://user-images.githubusercontent.com/12746591/98444203-b6807f80-2110-11eb-9f82-7b561eaf713f.png)
![piece7](https://user-images.githubusercontent.com/12746591/98444202-b5e7e900-2110-11eb-9f1f-6eda3d85db1a.png)
![piece8](https://user-images.githubusercontent.com/12746591/98444201-b54f5280-2110-11eb-9d18-53ffa66da61f.png)
![piece9](https://user-images.githubusercontent.com/12746591/98444200-b4b6bc00-2110-11eb-9968-2a8ead9cc707.png)
![piece10](https://user-images.githubusercontent.com/12746591/98444198-b41e2580-2110-11eb-9848-67cbb9c5f064.png)
![piece11](https://user-images.githubusercontent.com/12746591/98444196-b41e2580-2110-11eb-8c22-9397db6a7dce.png)
![piece12](https://user-images.githubusercontent.com/12746591/98444194-b3858f00-2110-11eb-8940-bd61b7fcf199.png)
</details>

There are a couple of jigsaw puzzle generators to produce these SVG paths. For example:
https://draradech.github.io/jigsaw/index.html

The only drawback of that version is that it combines all SVG paths into a single large path. If you are looking for a simplified generator with the paths separated, you could try this one:
https://kleisauke.nl/jigsaw-generator/

**Comment by hzm199822** [comment]
/usr/share/lua/5.1/vips.lua:5: libvips.so: cannot open shared object file: No such file or directory
stack traceback:
        [C]: in function 'load'
        /usr/share/lua/5.1/vips.lua:5: in main chunk
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: at 0x00404e90

**Comment by hzm199822** [comment]
I have compiled and installed the source code, but this error still occurs

**Comment by hzm199822** [comment]
However, after make install, it is generated under / usr / local / lib libvips.so 42.12.3, and two soft links appear
![image](https://user-images.githubusercontent.com/68108652/98676756-f9538900-2396-11eb-8117-095df3248a4a.png)

**Comment by hzm199822** [comment]
![image](https://user-images.githubusercontent.com/68108652/98676809-0c665900-2397-11eb-9cae-1e39a98430a1.png)

**Comment by hzm199822** [comment]
vips/Image_methods.lua:137: VipsForeignLoad: "/jpg/bg_2.jpg" is not a known file format

**Comment by hzm199822** [comment]
filename=/jpg/bg_2.jpg

I use
local image = vips.Image.new_ from_ file(filename)
however
vips/Image_ methods.lua:137 : VipsForeignLoad: "/jpg/bg_ 2.jpg" is not a known file format

**Comment by hzm199822** [comment]
![image](https://user-images.githubusercontent.com/68108652/98906344-d68cb600-24f7-11eb-96c9-0a1e884523a2.png)

![image](https://user-images.githubusercontent.com/68108652/98906524-28cdd700-24f8-11eb-8b56-4f7a2255b636.png)

the type(name)is cdata
Explain that the problem is
vips_ foreign_ find_ load

**Comment by hzm199822** [comment]
![image](https://user-images.githubusercontent.com/68108652/98906597-5155d100-24f8-11eb-9481-4e8ee7b8a2fe.png)
So what's the problem?

**Comment by jcupitt** [comment]
Perhaps you've not built libvips with JPEG support, or perhaps you're not passing the correct path. `"/jpg/bg_ 2.jpg"` looks wrong, for example, unless you really do have a directory called `/jpg`.

**Comment by rolandlo** [comment]
Closing the issue, since the problem appears to be solved.
