### ISSUE TITLE
Can I use lua rather than luajit?

### ISSUE THREAD

**Issue by maobaoqi** [libvips/lua-vips#40]
luajit is fast but old，I make several packages based on lua5.4. Can I use the libvips lua bindings with official lua？thanks

**Comment by jcupitt** [comment]
Hi @maobaoqi,

lua-vips uses luajit's FFI system, so as long as there's a Lua rock that implements a luajit-compatible FFI API, it should work.

I remember looking at this a year or two ago and not finding something suitable, but perhaps the situation is better now.

**Comment by maobaoqi** [comment]
@jcupitt thanks for reply. I found that there is a package called luaffi which maybe support newer official lua. so could I use this luaffi with libvips lua binding and to avoid luajit？

**Comment by jcupitt** [comment]
I'd think so, though you might need to do a bit of work. lua-vips is only 1500 lines of code so it shouldn't be too painful.

**Comment by maobaoqi** [comment]
ok,I will try. thanks you!

**Comment by jcupitt** [comment]
If you get it working, a PR would be very welcome.
