### ISSUE TITLE
autorotate - does not work

### ISSUE THREAD

**Issue by uasan** [libvips/lua-vips#6]
```LUA
vips = require "vips"

local image = vips.Image.jpegload("/var/www/Portrait_5.jpg", {autorotate = true})

vips.Image.jpegsave(image, "/var/www/normal.jpg", {Q = 60, strip = true, optimize_coding = true})
```

File saved `normal.jpg` - not rotated

Collections test images
https://github.com/recurser/exif-orientation-examples/

**Comment by jcupitt** [comment]
Hello, yes, vips just does the simple rotations, it doesn't implement all the exif mirror modes.

**Comment by uasan** [comment]
> vips just does the simple rotations, it doesn't implement all the exif mirror modes.

I have to handle this in my code, or in the future, a mirrored auto-rotation is planned, in `libvips`? :)

**Comment by jcupitt** [comment]
Do you have real images which use mirror and flip? I've never seen one, there are just a few synthetic images with the tag set.

**Comment by uasan** [comment]
Yes, you are right, it seems to be synthetics, I did not understand the term - `mirror`

Thank.
